### ISSUE TITLE
Updating of Loan Agreement

### ISSUE THREAD

**Issue by sashkoif** [Mangosoft-team/Demo#39]
I try to make PATCH request, at firts time I get this:

```
2019-06-28 22:00:08 | ERROR | ec-9 | troller.loan.LoanController:212   | Nominal for facility (38) is zero or less than zero
javax.validation.ValidationException: Nominal for facility (38) is zero or less than zero
        at de.varengold.cdl.core.model.contract.loanAgreement.facility.CreditFacility.validateNominal(CreditFacility.java:227)
        at de.varengold.cdl.core.model.contract.loanAgreement.facility.CreditFacility.validate(CreditFacility.java:216)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at de.varengold.cdl.core.model.contract.loanAgreement.LoanAgreement.validate(LoanAgreement.java:264)
        at de.varengold.cdl.core.model.contract.loanAgreement.LoanAgreementService.update(LoanAgreementService.java:73)
        at de.varengold.cdl.core.model.contract.loanAgreement.LoanAgreementService$$FastClassBySpringCGLIB$$3c1aec25.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
```

After that I use POSTMAN and fix nominal value to 1.00, so now I get this:

```
2019-06-28 22:09:55 | WARN  | ec-4 | jdbc.spi.SqlExceptionHelper:137   | SQL Error: 335544517, SQLState: HY000
2019-06-28 22:09:55 | ERROR | ec-4 | jdbc.spi.SqlExceptionHelper:142   | exception 48; EXC_INCON_THRESHOLDENTRY; Inkonsistente Angabe zu einem Schwellenwert; At trigger 'LOAN_KUENDIGUNGSGRUENDE_BIU0' line: 12, col: 66 [SQLState:HY000, ISC error code:335544517]
2019-06-28 22:09:55 | INFO  | ec-4 | .internal.AbstractBatchImpl:201   | HHH000010: On release of batch it still contained JDBC statements
2019-06-28 22:09:55 | ERROR | ec-4 | ExceptionMapperStandardImpl:39    | HHH000346: Error during managed flush [org.hibernate.exception.GenericJDBCException: could not execute statement]
2019-06-28 22:09:55 | ERROR | ec-4 | troller.loan.LoanController:212   | could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
org.springframework.orm.jpa.JpaSystemException: could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
```

**Comment by CT-VG** [comment]
The important part is this:
At trigger 'LOAN_KUENDIGUNGSGRUENDE_BIU0'
Inkonsistente Angabe zu einem Schwellenwert -> Inconsistent indication of a threshold value

So you are trying to insert a cancellation reason with a threshold for a loan.
But there is a validation which checks the following: 
CancellationReason.thresholdYN == "N" then you cannot set Cancellation.threshold
But to implement this the threshold must be nullable which is not not possible atm. -> BUG
A fix will be available in the Version.

Also after some reconciliation I remove the setter for the 
de.varengold.cdl.core.model.cancellation.Cancellation class, please use the AllArgsConstructor and create a new object.
